FROM python:3.11

WORKDIR /app

COPY requirements.base.txt /app/

# Install required Python packages
RUN pip install --no-cache-dir -r requirements.base.txt
RUN pip install --no-cache-dir git+https://github.com/hexrd/hexrd.git

CMD ["echo", "Base image built successfully"]

