system:
  redis_host: lnx202.classe.cornell.edu
  redis_port: 6379
  db_host: lnx202.classe.cornell.edu
  db_name: mtt_db
  db_user: dbanco
  db_pwd: password
  mtt_dir: /nfs/chess/user/dbanco/SpotfetchMTT
  singularity_dir: singularity_system
  sif_dir: sif
  app_dir: app
  postgres_dir: postgres_data
  region_dir: region_files
  tracker_state_dir: tracker_states
  num_trackers: 1

detector:
  name: dexela
  data_dir: /nfs/chess/raw/2025-1/id3a/shanks-3731-d/ti-2-test
  yaml_dir: /nfs/chess/aux/cycles/2025-1/id3a/shanks-3731-d/reduced_data/parameter_files
  yaml_file: ceo2_dexela_instr_032025.yml
  start_frame: 0
  starting_scan: 14
  scan_info_file: rams2-slew_ome
  im_size: [4000, 6500]
  
 
rings:
  - name: ring1
    tth_deg: 3.63
    tth_width: 35
    ome_start: 0
    ome_end: 40
    ome_size: 10
    eta_start: -180
    eta_end: 180
    num_eta_regions: 4

  - name: ring2
    tth_deg: 4.10
    tth_width: 40
    tth_width: 35
    ome_start: 0
    ome_end: 40
    ome_size: 10
    eta_start: -180
    eta_end: 180
    num_eta_regions: 2
